import { StyleSheet } from "react-native";

export const colors = {
  canvas: "#F5F8FA",
  surface: "#FFFFFF",
  ink: "#172B3A",
  muted: "#647783",
  line: "#E1E9EC",
  blue: "#0876A8",
  blueDark: "#07577D",
  bluePale: "#E4F3F9",
  green: "#08785A",
  greenPale: "#E2F5ED",
  amber: "#A65C00",
  amberPale: "#FFF2DC",
  red: "#B83D3D",
};

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.canvas },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 28, gap: 18 },
  topBar: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brand: { flexDirection: "row", alignItems: "center", gap: 9 },
  brandIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.blue,
  },
  brandText: { color: colors.ink, fontSize: 20, fontWeight: "800" },
  location: { color: colors.muted, fontSize: 12, marginTop: 2 },
  heading: { color: colors.ink, fontSize: 25, lineHeight: 32, fontWeight: "800" },
  subheading: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  sectionHeading: { color: colors.ink, fontSize: 18, fontWeight: "700" },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
    gap: 13,
  },
  hero: {
    borderRadius: 18,
    padding: 21,
    gap: 12,
    backgroundColor: colors.blueDark,
  },
  heroTitle: { color: colors.surface, fontSize: 26, lineHeight: 32, fontWeight: "800" },
  heroText: { color: "#DCEEF5", fontSize: 14, lineHeight: 21 },
  eyebrow: { color: colors.blue, fontSize: 11, fontWeight: "800", letterSpacing: 0.6 },
  row: { flexDirection: "row", alignItems: "center", gap: 10 },
  between: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  divider: { height: 1, backgroundColor: colors.line },
  button: {
    minHeight: 52,
    paddingHorizontal: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    backgroundColor: colors.blue,
  },
  buttonGreen: { backgroundColor: colors.green },
  buttonLight: { backgroundColor: colors.bluePale },
  buttonText: { color: colors.surface, fontSize: 15, fontWeight: "700" },
  buttonTextLight: { color: colors.blueDark, fontSize: 15, fontWeight: "700" },
  option: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  optionSelected: { borderColor: colors.blue, backgroundColor: colors.bluePale },
  optionText: { color: colors.muted, fontSize: 13, fontWeight: "600" },
  optionTextSelected: { color: colors.blueDark },
  label: { color: colors.ink, fontSize: 14, fontWeight: "700" },
  small: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  price: { color: colors.blueDark, fontSize: 26, fontWeight: "800" },
  input: {
    minHeight: 50,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 10,
    paddingHorizontal: 13,
    color: colors.ink,
    backgroundColor: colors.surface,
  },
  avatar: {
    width: 54,
    height: 54,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.greenPale,
  },
  avatarText: { color: colors.green, fontSize: 17, fontWeight: "800" },
  badge: {
    alignSelf: "flex-start",
    borderRadius: 30,
    backgroundColor: colors.greenPale,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  badgeText: { color: colors.green, fontSize: 11, fontWeight: "700" },
  splashPage: { justifyContent: "space-between", paddingHorizontal: 22, paddingBottom: 20 },
  splashTop: { gap: 18 },
  splashArt: { minHeight: 300, alignItems: "center", justifyContent: "center", position: "relative" },
  splashRing: { width: 218, height: 218, borderRadius: 109, alignItems: "center", justifyContent: "center", backgroundColor: colors.bluePale, borderWidth: 1, borderColor: "#C7E4F0" },
  splashPhoto: { width: 210, height: 210, borderRadius: 105 },
  avatarPhoto: { width: "100%", height: "100%", borderRadius: 18 },
  splashBadge: { position: "absolute", left: "19%", bottom: "24%", width: 46, height: 46, borderRadius: 23, alignItems: "center", justifyContent: "center", backgroundColor: colors.surface, elevation: 3 },
  splashSparkle: { position: "absolute", right: "19%", top: "22%", width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: colors.amberPale },
  splashContent: { gap: 15, paddingBottom: 10 },
  splashTitle: { color: colors.ink, fontSize: 31, lineHeight: 39, fontWeight: "800" },
  centerLink: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 4 },
  linkText: { color: colors.blue, fontSize: 14, fontWeight: "700" },
  heroKicker: { color: "#BCE7F5", fontSize: 10, fontWeight: "800", letterSpacing: 0.8 },
  heroProof: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 2 },
  heroProofText: { color: "#E3F5EE", fontSize: 12, fontWeight: "600" },
  choiceGroup: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  counterButton: { width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: colors.bluePale },
  counterButtonActive: { backgroundColor: colors.blue },
  counterValue: { minWidth: 30, textAlign: "center", color: colors.ink, fontSize: 16, fontWeight: "700" },
  estimate: { borderRadius: 12, backgroundColor: colors.bluePale, padding: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  estimateTime: { alignItems: "flex-end", gap: 4 },
  featureStrip: { flexDirection: "row", alignItems: "center", gap: 11, padding: 14, backgroundColor: colors.greenPale, borderRadius: 12 },
  featureCopy: { flex: 1, gap: 2 },
  screenHeadingBlock: { gap: 6, paddingTop: 8, paddingBottom: 2 },
  emptyState: { alignItems: "center", gap: 13, paddingHorizontal: 12, paddingVertical: 28, backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.line },
  emptyIcon: { width: 66, height: 66, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: colors.bluePale },
  infoRow: { flexDirection: "row", alignItems: "center", gap: 9, padding: 12, backgroundColor: colors.greenPale, borderRadius: 11 },
  accountPanel: { alignItems: "center", gap: 14, padding: 20, backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.line },
  avatarLarge: { width: 82, height: 82, borderRadius: 27 },
  avatarTextLarge: { fontSize: 24 },
  centerText: { textAlign: "center" },
  roleSwitch: { flexDirection: "row", padding: 4, borderRadius: 12, backgroundColor: "#E9EFF2", gap: 5 },
  roleChoice: { flex: 1, minHeight: 46, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, borderRadius: 9 },
  roleChoiceActive: { backgroundColor: colors.surface },
  forgotLink: { alignSelf: "flex-end", minHeight: 38, justifyContent: "center" },
  serviceOption: { minHeight: 70, flexDirection: "row", alignItems: "center", gap: 10, padding: 10, borderRadius: 11, borderWidth: 1, borderColor: colors.line },
  serviceOptionActive: { borderColor: colors.blue, backgroundColor: colors.bluePale },
  serviceIcon: { width: 40, height: 40, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: colors.canvas },
  serviceIconActive: { backgroundColor: colors.surface },
  flexOne: { flex: 1, gap: 4 },
  locationStrip: { minHeight: 48, flexDirection: "row", alignItems: "center", gap: 9, paddingHorizontal: 12, borderRadius: 10, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line },
  proCard: { padding: 15, gap: 12, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface },
  proDetails: { flex: 1, gap: 4 },
  proName: { color: colors.ink, fontSize: 15, fontWeight: "700" },
  rating: { flexDirection: "row", alignItems: "center", gap: 4 },
  ratingText: { color: colors.ink, fontSize: 13, fontWeight: "700" },
  proPrice: { marginTop: 3, color: colors.blueDark, fontSize: 15, fontWeight: "800" },
  smallButton: { minHeight: 42, flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 10, borderRadius: 9, backgroundColor: colors.bluePale },
  smallButtonText: { color: colors.blueDark, fontSize: 13, fontWeight: "700" },
  profileHero: { alignItems: "center", gap: 10, paddingVertical: 8 },
  profileName: { color: colors.ink, fontSize: 23, fontWeight: "800", textAlign: "center" },
  profileStats: { flexDirection: "row", gap: 12 },
  stat: { flex: 1, padding: 12, borderRadius: 10, backgroundColor: colors.canvas },
  statValue: { color: colors.blueDark, fontSize: 19, fontWeight: "800" },
  availabilityCard: { minHeight: 72, paddingHorizontal: 14, paddingVertical: 10, flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 13, borderWidth: 1 },
  available: { backgroundColor: colors.greenPale, borderColor: "#BCE8D4" },
  unavailable: { backgroundColor: colors.amberPale, borderColor: "#F1D4A6" },
  detailsGrid: { gap: 8 },
  statusIcon: { width: 56, height: 56, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: colors.greenPale },
  metricsRow: { flexDirection: "row", gap: 8 },
  metric: { flex: 1, alignItems: "center", gap: 4, padding: 12, borderRadius: 11, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line },
  metricValue: { color: colors.blueDark, fontSize: 16, fontWeight: "800" },
});